---
- name: Allow password authentication
  lineinfile: >-
    dest=/etc/ssh/sshd_config
    regexp="^PasswordAuthentication"
    line="PasswordAuthentication yes"
    state=present

- name: Restart ssh
  service: >-
    name=ssh
    state=restarted
