---

# Installs mariadb.

- name: Configure instance(s)
  hosts: all
  sudo: True
  gather_facts: True
  vars:
    MARIADB_HOST_PRIV: '192.168.122.113'
    MARIADB_LISTEN_ALL: true
  roles:
    - mariadb
