---
- name: Deploy edxapp
  hosts: all
  sudo: True
  gather_facts: True
  vars:
    service_variants_enabled:
      - lms
      - cms
    EDXAPP_WORKERS:
      lms: 16
  roles:
    - { role: 'edxapp', celery_worker: True }
